
<div id="detail">
    <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action'=>'index', 'id' => $product->productlist_id));?>">zpět</a>
    <div id="options">
        <a href="<?php echo $this->url('admin', array('controller' => 'product', 'action'=>'delete', 'id' => $product->id));?>" class="icon untick">smazat</a>
        <span class="icon edit opener">editovat</span>
    </div>
    
    <h2>
        <?php if ($product->published) { ?>
                    <a class="icon tick ajax" href="<?php echo $this->url('admin', array('controller' => 'product', 'action'=>'publish', 'id' => $product->id));?>"></a>
            <?php } else { 
            ?>
                    <a class="icon untick ajax" href="<?php echo $this->url('admin', array('controller' => 'product', 'action'=>'publish', 'id' => $product->id));?>"></a>
            <?php } ?> 
        <?= $product->title; ?>
    </h2>
    
    <div class="content">
        <div class="box">
            <?php $images->buffer();
            foreach ($images as $image) :
                    if($image->product_id == $product->id) : ?>
                        <img src="<?= $this->basePath() . $image->path . 'thumb/' . $image->name; ?>" alt="" />
            <?php endif; endforeach; ?>
        </div>
        <div class="box">
            <p><?= $product->description; ?></p>
            <p><?= $product->price; ?> Kč</p>
            
            <p><?= $product->created; ?></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="content">
        <p><?= $product->text; ?></p>
    </div>
</div>


<script>
// increase the default animation speed to exaggerate the effect
$.fx.speeds._default = 1000;
$(function() {
    $( "#dialog" ).dialog({
            autoOpen: false,
            show: "explode",
            hide: "explode",
            closeText: "hide",
            draggable: false,
            resizable: false,
            modal: true,
            width: 600,
            title: "Editace produktu"
    });

    $( ".opener" ).click(function() {
            $( "#dialog" ).dialog( "open" );
            return false;
    });
});
</script>

<div id="dialog">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    array(
        'controller' => 'product',
        'action' => 'detail',
        'id' => $id
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('security'));
echo $this->formRow($form->get('title')) . '</br>';
echo $this->formRow($form->get('description')) . '</br>';
echo $this->formRow($form->get('text')) . '</br>';
echo $this->formRow($form->get('price')) . '</br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>