<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    array(
        'controller' => 'productList',
        'action' => 'index'
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title')) . '<br />';
echo $this->formRow($form->get('categorylist_id'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>