<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Editace uživatele';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    array(
        'controller' => 'user',
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username')) . '<br />';
echo $this->formRow($form->get('name')) . '<br />';
echo $this->formRow($form->get('role')) . '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();