<img id="foto" src="<?php echo $this->basePath(); ?>/images/foto.jpg" alt="" />
<div id="contentIn">
    <h1>O nás</h1>
    <p>
        <?php echo $this->escape($date); ?>Firma Kučera – Zámečnictví byla založena v roce 1957 jako rodinný podnik, který se ve své době
        zabýval nejen kovovýrobou, ale fungoval také jako kovárna. Firma měla mnoho učňů a dělala čest
        svému řemeslu. Postupně byla výroba rozšiřována, nicméně plánované otevření zinkovny bylo
        nakonec v roce 1968 přerušeno.
    </p>
    <p>
        Jako všechny soukromé podniky se i naše dílna v roce 1968 ocitla pod správou komunálu. Stroje
        byly znárodněny, plány zničeny a rozvoj se zastavil na dalších dvacet let. V roce 1991 se podařilo
        vrátit firmu do původních kolejí, tedy do soukromých rukou rodiny Kučerových. Bohužel, s poměrně
        velkým handicapem v podobě zabavených strojů, které firma musela od státu odkoupit. Naštěstí naše
        kvalitní výrobky brzy vrátily firmě její dobré jméno a nic nebránilo jejímu dalšímu rozvoji.
    </p>
    <p>
        V dnešní době se zabýváme nejen výrobou kovového zboží, ale i expertním otevíráním dveří a
        montáží bezpečnostních systémů. Tradice předávaná z otců na syny se odráží v kvalitním zpracování
        zakázek a v pečlivé odborné montáži našich výrobků.
    </p>
</div>