<div id="contentIn">
    <h1>Kontaktní formulář</h1>
    <p>Pomocí tohoto formuláře nám můžete napsat vzkaz, na který Vám odpovíme v co možná nejkraším čase.</p>

        <div class="contact-form">
           <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('application', array('action' => 'contact')));
                $form->prepare();
                
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('name'));
                echo $this->formRow($form->get('email'));
                echo $this->formRow($form->get('subject'));
                echo $this->formRow($form->get('message'));
                echo $this->formSubmit($form->get('send'));
                echo $this->form()->closeTag();
            ?>
        </div>

</div>