
<img id="foto" src="<?php echo $this->basePath(); ?>/images/foto.jpg" alt="" />
    <h1>Hlavní stránka</h1>
    <p>Vítejte na stránkách rodinné firmy Kučera – Zámečnictví.</p>
    <p>
        Zabýváme se výrobou kovového zboží, expertním otevíráním dveří, včetně montáží bezpečnostních
        systémů, a také odbornou montáží našich výrobků. Nabízíme výrobu garážových vrat, plotových
        bran, plotových dílů, různých konstrukcí, grilů a dalšího drobného kovového zboží. Dále pak napínání
        plotů, sváření, a to nejen elektrickým obloukem, ale i autogenem. Vyrábíme klíče FAB, dozické klíče
        i autoklíče. Naše výrobky se vyznačují vysokou kvalitou a díky nižším nákladům rodinného podniku i
        velice příznivou cenou. Přijďte nás navštívit a přesvědčte se sami.
    </p> 