<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    array(
        'controller' => 'sign',
        'action' => 'index'
    )
));

if ($error)
{
    echo $error;
}
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('name')) . '</br>';
echo $this->formRow($form->get('password')) . '</br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>